# Base image with Python
FROM python
# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the application code into the container
COPY . .
# Command to run the getImages.py first and then train.py
#CMD python getImages.py && python train.py
